name: Test

on:
  push:
    branches:
      - main

jobs:
  TestBranch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'release-notes'

