name: Test

on:
  push:
    branches:
      - main
      - deploy-*

jobs:
  TestBranch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Determine if commit is tagged
      run: |
        git fetch --all >/dev/null 2>&1
        IS_TAGGED_COMMIT=$(if git describe --exact-match $GITHUB_SHA >/dev/null 2>&1; then echo "true"; else echo "false"; fi)
        echo "IS_TAGGED_COMMIT=$IS_TAGGED_COMMIT" >> $GITHUB_ENV
        if [ "$IS_TAGGED_COMMIT" = "true" ]; then echo "This commit is tagged, triggering release."; else echo "This commit is NOT tagged."; fi
        if [ "$IS_TAGGED_COMMIT" = "true" ]; then echo "TAG_STRING=$(git describe --exact-match $GITHUB_SHA)" >> $GITHUB_ENV ; fi

    - name: Echo Tag Version
      if: ${{ env.IS_TAGGED_COMMIT == 'true' }}
      run: |
        echo ${{ env.TAG_STRING }}

    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'deploy-${{ env.TAG_STRING }}'
